## Group Project Code:

In [2]:
library(tidyverse)

── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ ggplot2 3.2.1     ✔ purrr   0.3.2
✔ tibble  2.1.3     ✔ dplyr   0.8.3
✔ tidyr   0.8.3     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.4.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [3]:
# See if we can get away with loading as regular csv file
Pollution <- read_csv("Pollution.csv")

Warning message:
“Missing column names filled in: 'X1' [1], 'X2' [2]”Warning message:
“Duplicated column names deduplicated: 'Ambient and household air pollution attributable death rate (per 100 000 population)' => 'Ambient and household air pollution attributable death rate (per 100 000 population)_1' [4], 'Ambient and household air pollution attributable death rate (per 100 000 population)' => 'Ambient and household air pollution attributable death rate (per 100 000 population)_2' [5], 'Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)' => 'Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)_1' [7], 'Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)' => 'Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)_2' [8]”Parsed with column specification:
cols(
  X1 = col_character(),
  X2 = col_character(),
  `Ambient and household air pollution attributable death rate (per 100 000 population)` = col_character(),
  `Ambient and household air pollution attributable death rate (per 100 000 population)_1` = col_character(),
  `Ambient and household air pollution attributable death rate (per 100 000 population)_2` = col_character(),
  `Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)` = col_character(),
  `Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)_1` = col_character(),
  `Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)_2` = col_character()
)

In [4]:
Pollution %>% head() # this is messy, do we need to load it a different way?
#So multiple problems in reading as a csv. But think we can work with it like this.

  X1          X2
1 NA          NA
2 Country     Cause
3 Afghanistan Total
4 Afghanistan Lower respiratory infections
5 Afghanistan Trachea, bronchus, lung cancers
6 Afghanistan Ischaemic heart disease
  Ambient and household air pollution attributable death rate (per 100 000 population)
1 2016
2 Both sexes
3 95[ 85–104]
4 31[ 26–36]
5 2[ 1–2]
6 39[ 33–44]
  Ambient and household air pollution attributable death rate (per 100 000 population)_1
1 2016
2 Male
3 96[ 85–106]
4 29[ 24–34]
5 2[ 2–3]
6 42[ 36–48]
  Ambient and household air pollution attributable death rate (per 100 000 population)_2
1 2016
2 Female
3 95[ 85–104]
4 33[ 27–38]
5 1[ 1–1]
6 35[ 30–39]
  Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)
1 2016
2 Both sexes
3 211[ 189–231]
4 32[ 26–36]
5 4[ 3–5]
6 107[ 92–121]
  Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)_1
1 2016
2 Male
3 229[ 205–254]
4 33[ 27–38]
5 6[ 4–7]
6 120[ 103–138]
  Ambient and household air pollution attributable death rate (per 100 000 population, age-standardized)_2
1 2016
2 Female
3 195[ 174–214]
4 31[ 25–35]
5 2[ 2–3]
6 94[ 81–106]

In [5]:
# To start, we can slice of the first two rows as these are not needed, this information can be put in (to be created) read.me file
Pollution <- read_csv("Pollution.csv", col_names=FALSE)

Pollution <- Pollution %>%
    slice(3:nrow(Pollution))

Pollution %>%
    head()

Parsed with column specification:
cols(
  X1 = col_character(),
  X2 = col_character(),
  X3 = col_character(),
  X4 = col_character(),
  X5 = col_character(),
  X6 = col_character(),
  X7 = col_character(),
  X8 = col_character()
)

  X1          X2                              X3          X4
1 Country     Cause                           Both sexes  Male
2 Afghanistan Total                           95[ 85–104] 96[ 85–106]
3 Afghanistan Lower respiratory infections    31[ 26–36]  29[ 24–34]
4 Afghanistan Trachea, bronchus, lung cancers 2[ 1–2]     2[ 2–3]
5 Afghanistan Ischaemic heart disease         39[ 33–44]  42[ 36–48]
6 Afghanistan Stroke                          16[ 13–18]  14[ 12–16]
  X5          X6            X7            X8
1 Female      Both sexes    Male          Female
2 95[ 85–104] 211[ 189–231] 229[ 205–254] 195[ 174–214]
3 33[ 27–38]  32[ 26–36]    33[ 27–38]    31[ 25–35]
4 1[ 1–1]     4[ 3–5]       6[ 4–7]       2[ 2–3]
5 35[ 30–39]  107[ 92–121]  120[ 103–138] 94[ 81–106]
6 18[ 15–20]  45[ 39–52]    44[ 37–50]    47[ 40–54]

In [6]:
# Cool, but we still need to remove/make first row the column names
Pollution <- Pollution %>%
    rename(
        Country = X1,
        Cause = X2,
        Both_sexes = X3,
        Male = X4,
        Female = X5,
        Both_sexes_standardised = X6,
        Male_standardised = X7,
        Female_standardised = X8
    ) %>%
    slice(2:nrow(Pollution))

Pollution %>% head()

  Country     Cause                                 Both_sexes  Male
1 Afghanistan Total                                 95[ 85–104] 96[ 85–106]
2 Afghanistan Lower respiratory infections          31[ 26–36]  29[ 24–34]
3 Afghanistan Trachea, bronchus, lung cancers       2[ 1–2]     2[ 2–3]
4 Afghanistan Ischaemic heart disease               39[ 33–44]  42[ 36–48]
5 Afghanistan Stroke                                16[ 13–18]  14[ 12–16]
6 Afghanistan Chronic obstructive pulmonary disease 7[ 5–8]     7[ 4–9]
  Female      Both_sexes_standardised Male_standardised Female_standardised
1 95[ 85–104] 211[ 189–231]           229[ 205–254]     195[ 174–214]
2 33[ 27–38]  32[ 26–36]              33[ 27–38]        31[ 25–35]
3 1[ 1–1]     4[ 3–5]                 6[ 4–7]           2[ 2–3]
4 35[ 30–39]  107[ 92–121]            120[ 103–138]     94[ 81–106]
5 18[ 15–20]  45[ 39–52]              44[ 37–50]        47[ 40–54]
6 7[ 6–8]     23[ 18–28]              26[ 16–34]        21[ 17–25]

In [7]:
# Idea: fix numbers first then any filtering and creating new data frames will use already fixed numbers?
# Will need to use regex and string_extract
Pollution <- Pollution %>%
    mutate(
        Both_sexes_value = str_extract(Both_sexes, "\\d+"),
        Both_sexes_lower = str_replace(str_extract(Both_sexes, "\\[ \\d+"), "[\\[]", ""), 
        Both_sexes_upper = str_replace(str_extract(Both_sexes, "\\–\\d+"), "–", ""),
        Male_value = str_extract(Male, "\\d+"),
        Male_lower = str_replace(str_extract(Male, "\\[ \\d+"), "[\\[]", ""), 
        Male_upper = str_replace(str_extract(Male, "\\–\\d+"), "–", ""),  
        Female_value = str_extract(Male, "\\d+"),
        Female_lower = str_replace(str_extract(Male, "\\[ \\d+"), "[\\[]", ""), 
        Female_upper = str_replace(str_extract(Male, "\\–\\d+"), "–", ""),
        Both_sexes_standardised_value = str_extract(Both_sexes_standardised, "\\d+"),
        Both_sexes_standardised_lower = str_replace(str_extract(Both_sexes_standardised, "\\[ \\d+"), "[\\[]", ""), 
        Both_sexes_standardised_upper = str_replace(str_extract(Both_sexes_standardised, "\\–\\d+"), "–", ""),
        Male_standardised_value = str_extract(Male_standardised, "\\d+"),
        Male_standardised_lower = str_replace(str_extract(Male_standardised, "\\[ \\d+"), "[\\[]", ""), 
        Male_standardised_upper = str_replace(str_extract(Male_standardised, "\\–\\d+"), "–", ""),
        Female_standardised_value = str_extract(Male_standardised, "\\d+"),
        Female_standardised_lower = str_replace(str_extract(Male_standardised, "\\[ \\d+"), "[\\[]", ""), 
        Female_standardised_upper = str_replace(str_extract(Male_standardised, "\\–\\d+"), "–", ""),
          )

Pollution %>% head()
#gsub("[\\[\\]]", "", regmatches(j, gregexpr("\\[.*?\\]", j))[[1]])
#str_replace(str_extract(Both_sexes, "\\[ \\d+ \\]"), "[\\[]", "")
#Both_sexes_upper = str_replace(str_extract(Both_sexes, "\\[.*?\\]"), "[\\[ \\d+.]", "")

  Country     Cause                                 Both_sexes  Male
1 Afghanistan Total                                 95[ 85–104] 96[ 85–106]
2 Afghanistan Lower respiratory infections          31[ 26–36]  29[ 24–34]
3 Afghanistan Trachea, bronchus, lung cancers       2[ 1–2]     2[ 2–3]
4 Afghanistan Ischaemic heart disease               39[ 33–44]  42[ 36–48]
5 Afghanistan Stroke                                16[ 13–18]  14[ 12–16]
6 Afghanistan Chronic obstructive pulmonary disease 7[ 5–8]     7[ 4–9]
  Female      Both_sexes_standardised Male_standardised Female_standardised
1 95[ 85–104] 211[ 189–231]           229[ 205–254]     195[ 174–214]
2 33[ 27–38]  32[ 26–36]              33[ 27–38]        31[ 25–35]
3 1[ 1–1]     4[ 3–5]                 6[ 4–7]           2[ 2–3]
4 35[ 30–39]  107[ 92–121]            120[ 103–138]     94[ 81–106]
5 18[ 15–20]  45[ 39–52]              44[ 37–50]        47[ 40–54]
6 7[ 6–8]     23[ 18–28]              26[ 16–34]        21[ 17–25]
  Both_sexes_value Both_sexes_lower ⋯ Female_upper
1 95                85              ⋯ 106
2 31                26              ⋯ 34
3 2                 1               ⋯ 3
4 39                33              ⋯ 48
5 16                13              ⋯ 16
6 7                 5               ⋯ 9
  Both_sexes_standardised_value Both_sexes_standardised_lower
1 211                            189
2 32                             26
3 4                              3
4 107                            92
5 45                             39
6 23                             18
  Both_sexes_standardised_upper Male_standardised_value Male_standardised_lower
1 231                           229                      205
2 36                            33                       27
3 5                             6                        4
4 121                           120                      103
5 52                            44                       37
6 28                            26                       16
  Male_standardised_upper Female_standardised_value Female_standardised_lower
1 254                     229                        205
2 38                      33                         27
3 7                       6                          4
4 138                     120                        103
5 50                      44                         37
6 34                      26                         16
  Female_standardised_upper
1 254
2 38
3 7
4 138
5 50
6 34

In [8]:
Pollution <- Pollution %>%
    select(
        -Both_sexes,
        -Male,
        -Female,
        -Both_sexes_standardised,
        -Male_standardised,
        -Female_standardised
    )
Pollution %>% head()

  Country     Cause                                 Both_sexes_value
1 Afghanistan Total                                 95
2 Afghanistan Lower respiratory infections          31
3 Afghanistan Trachea, bronchus, lung cancers       2
4 Afghanistan Ischaemic heart disease               39
5 Afghanistan Stroke                                16
6 Afghanistan Chronic obstructive pulmonary disease 7
  Both_sexes_lower Both_sexes_upper Male_value Male_lower Male_upper
1  85              104              96          85        106
2  26              36               29          24        34
3  1               2                2           2         3
4  33              44               42          36        48
5  13              18               14          12        16
6  5               8                7           4         9
  Female_value Female_lower Female_upper Both_sexes_standardised_value
1 96            85          106          211
2 29            24          34           32
3 2             2           3            4
4 42            36          48           107
5 14            12          16           45
6 7             4           9            23
  Both_sexes_standardised_lower Both_sexes_standardised_upper
1  189                          231
2  26                           36
3  3                            5
4  92                           121
5  39                           52
6  18                           28
  Male_standardised_value Male_standardised_lower Male_standardised_upper
1 229                      205                    254
2 33                       27                     38
3 6                        4                      7
4 120                      103                    138
5 44                       37                     50
6 26                       16                     34
  Female_standardised_value Female_standardised_lower Female_standardised_upper
1 229                        205                      254
2 33                         27                       38
3 6                          4                        7
4 120                        103                      138
5 44                         37                       50
6 26                         16                       34

In [11]:
Pollution[, c(3:20)] <- sapply(Pollution[, c(3:20)], as.integer)
Pollution %>% head()

#for(i in 3:20){
    
#}

  Country     Cause                                 Both_sexes_value
1 Afghanistan Total                                 95
2 Afghanistan Lower respiratory infections          31
3 Afghanistan Trachea, bronchus, lung cancers        2
4 Afghanistan Ischaemic heart disease               39
5 Afghanistan Stroke                                16
6 Afghanistan Chronic obstructive pulmonary disease  7
  Both_sexes_lower Both_sexes_upper Male_value Male_lower Male_upper
1 85               104              96         85         106
2 26                36              29         24          34
3  1                 2               2          2           3
4 33                44              42         36          48
5 13                18              14         12          16
6  5                 8               7          4           9
  Female_value Female_lower Female_upper Both_sexes_standardised_value
1 96           85           106          211
2 29           24            34           32
3  2            2             3            4
4 42           36            48          107
5 14           12            16           45
6  7            4             9           23
  Both_sexes_standardised_lower Both_sexes_standardised_upper
1 189                           231
2  26                            36
3   3                             5
4  92                           121
5  39                            52
6  18                            28
  Male_standardised_value Male_standardised_lower Male_standardised_upper
1 229                     205                     254
2  33                      27                      38
3   6                       4                       7
4 120                     103                     138
5  44                      37                      50
6  26                      16                      34
  Female_standardised_value Female_standardised_lower Female_standardised_upper
1 229                       205                       254
2  33                        27                        38
3   6                         4                         7
4 120                       103                       138
5  44                        37                        50
6  26                        16                        34

In [9]:
#create total database?
Pollution %>%
    filter(Cause == "Total") %>%
    select(-Cause) %>%
    head()

  Country             Both_sexes_value Both_sexes_lower Both_sexes_upper
1 Afghanistan         95                85              104
2 Albania             105               70              147
3 Algeria             40                31              70
4 Angola              67                58              76
5 Antigua and Barbuda 28                24              34
6 Argentina           37                28              49
  Male_value Male_lower Male_upper Female_value Female_lower Female_upper
1 96          85        106        96            85          106
2 118         81        164        118           81          164
3 43          34        74         43            34          74
4 65          55        74         65            55          74
5 31          26        37         31            26          37
6 39          30        51         39            30          51
  Both_sexes_standardised_value Both_sexes_standardised_lower
1 211                            189
2 68                             46
3 50                             39
4 119                            102
5 30                             25
6 27                             20
  Both_sexes_standardised_upper Male_standardised_value Male_standardised_lower
1 231                           229                      205
2 96                            82                       57
3 86                            55                       44
4 135                           120                      102
5 36                            37                       31
6 35                            36                       27
  Male_standardised_upper Female_standardised_value Female_standardised_lower
1 254                     229                        205
2 115                     82                         57
3 94                      55                         44
4 137                     120                        102
5 44                      37                         31
6 47                      36                         27
  Female_standardised_upper
1 254
2 115
3 94
4 137
5 44
6 47

In [11]:
Pollution %>%
    filter(Cause == "Total") %>%
    select(Country, Both_sexes_value, Male_value, Female_value, Both_sexes_standardised_value, Male_standardised_value, Female_standardised_value) %>%
    head()

  Country             Both_sexes_value Male_value Female_value
1 Afghanistan         95               96         96
2 Albania             105              118        118
3 Algeria             40               43         43
4 Angola              67               65         65
5 Antigua and Barbuda 28               31         31
6 Argentina           37               39         39
  Both_sexes_standardised_value Male_standardised_value
1 211                           229
2 68                            82
3 50                            55
4 119                           120
5 30                            37
6 27                            36
  Female_standardised_value
1 229
2 82
3 55
4 120
5 37
6 36